### ISSUE TITLE
yamlloader 1.5.0 states no minimum Python version but uses constructs that fail on older Python versions

### ISSUE THREAD

**Issue by andy-maier** [Phynix/yamlloader#58]
Note: Some environments still need to support Python 3.6, e.g. the fix branches of some of our projects.

yamlloader does not state a minimum supported Python version (it has no `requires-python` statement in its `pyproject.toml` file, and the Trove classifiers in that same file also do not indicate a minimum Python 3.x version). Therefore, pip installs it just fine on Python 3.6.

However, yamlloader version 1.5.0 started using Python constructs that require higher Python versions.

From the [log](https://github.com/pywbem/pywbem/actions/runs/12534725184/job/34955837417?pr=3246#step:10:96) of one of our projects, on Python 3.6:
```
python -c "import pywbem"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/pywbem/pywbem/pywbem/__init__.py", line 49, in <module>
    from ._cim_operations import *  # noqa: F403,F401
  File "/home/runner/work/pywbem/pywbem/pywbem/_cim_operations.py", line 167, in <module>
    from ._recorder import LogOperationRecorder
  File "/home/runner/work/pywbem/pywbem/pywbem/_recorder.py", line 36, in <module>
    import yamlloader
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/yamlloader/__init__.py", line 5, in <module>
    from . import ordereddict
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/yamlloader/ordereddict/__init__.py", line 3, in <module>
    from .dumpers import Dumper, SafeDumper, CDumper, CSafeDumper
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/yamlloader/ordereddict/dumpers.py", line 3
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

Please determine what your minimum Python version is and add that to the `pyproject.toml` file.
For example, if Python 3.8 is the minimum:

```
[project]
. . .
classifiers = [
    . . .
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.8"
```

**Comment by jonas-eschle** [comment]
Hi @andy-maier , thanks a lot, this was probably missed when we converted to the `pyproject.toml`, fixed. Gonna make a new release, 1.5.1 and yank the old one to prevent Python 3.6 to install a version newer than 1.4.x

**Comment by jonas-eschle** [comment]
Published, please feel free to close if it works or let me know if it doesn't
